version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build: ./django
    volumes:
      - ./django:/app
    user: django
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:latest

{% if cookiecutter.use_tasks == 'y' %}
  celeryworker:
    build: ./django
    user: django
    env_file: .env
    depends_on:
     - postgres
     - redis
    command: celery -A django.apps.tasks worker -l INFO
{% endif %}
